# -------------------------------------------------
# Authentication mechanisms
# -------------------------------------------------
auth_mechanisms = plain login

# -------------------------------------------------
# SQL authentication include
# -------------------------------------------------
!include auth-sql.conf.ext
