CREATE TABLE `email_confirmations` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `email` varchar(254) NOT NULL,
  `token_hash` binary(32) NOT NULL,
  `status` enum('pending','confirmed','expired') NOT NULL DEFAULT 'pending',
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `expires_at` datetime(6) NOT NULL,
  `confirmed_at` datetime(6) DEFAULT NULL,
  `request_ip` varbinary(16) DEFAULT NULL,
  `user_agent` varchar(255) DEFAULT NULL,
  `send_count` int(10) unsigned NOT NULL DEFAULT 1,
  `last_sent_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `attempts_confirm` int(10) unsigned NOT NULL DEFAULT 0,
  `active_pending` tinyint(4) GENERATED ALWAYS AS (case when `status` = 'pending' then 1 else NULL end) VIRTUAL,
  `intent` varchar(32) NOT NULL DEFAULT 'subscribe',
  `alias_name` varchar(64) DEFAULT NULL,
  `alias_domain` varchar(253) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_token_hash` (`token_hash`),
  UNIQUE KEY `uq_email_active_pending` (`email`,`active_pending`),
  KEY `idx_email_status` (`email`,`status`),
  KEY `idx_expires_at` (`expires_at`),
  KEY `idx_request_ip_created` (`request_ip`,`created_at`),
  KEY `idx_last_sent_at` (`last_sent_at`),
  KEY `idx_intent_email` (`intent`,`email`)
) ENGINE=InnoDB AUTO_INCREMENT=1124 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;